name: iOS CI with Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test iOS app
    runs-on: macos-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set Xcode version
      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_15.4.app

      # Step 3: Install CocoaPods dependencies
      - name: Install dependencies
        run: |
          sudo gem install cocoapods -v 1.12.1  # Adjust if needed
          pod install

      # Step 4: List Schemes (Debugging Step)
      - name: List Schemes
        run: xcodebuild -list -workspace ThoughtFlow.xcworkspace

      # Step 5: Build the app with code coverage enabled
      - name: Build the app with code coverage
        run: |
          xcodebuild -workspace ThoughtFlow.xcworkspace \
                     -scheme ThoughtFlow \
                     -sdk iphonesimulator \
                     -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
                     -enableCodeCoverage YES \
                     build

      # Step 6: Run unit tests with code coverage enabled
      - name: Run tests with code coverage
        run: |
          xcodebuild test -workspace ThoughtFlow.xcworkspace \
                          -scheme ThoughtFlowTests \
                          -destination 'platform=iOS Simulator,name=iPhone 14,OS=latest' \
                          -enableCodeCoverage YES

      # Step 7: Generate Code Coverage Report
      - name: Generate Code Coverage Report
        run: |
          xcrun xccov view --report --json build/Logs/Test/*.xcresult > coverage.json

      # Step 8: Upload Code Coverage Report
      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage.json

      # Step 9: Clean up derived data
      - name: Clean up
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData
